Repository CMU-313/nodebb-f24-d-buggers, pull requests merged in 2024-10, with the labels that each got.

#33 Adding testing procedures to userguide.md
  .gitignore
  dump.rdb
  userguide.md
Labels: documentation

#32 Implement Backend Feature for NodeBB Endorsement Button
  install/package.json
  public/src/client/account/endorsed.js
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/controllers/posts.js
  src/routes/api.js
  src/socket.io/posts.js
  test/posts.js
  test/topics.js
  test/topics/endorse.js
Labels: bug, enhancement

#34 Refactored/modified repo to ensure that GitHub Actions pass for proper deployment
  public/src/client/account/endorsed.js
  test/posts.js
  test/topics.js
  test/topics/endorse.js
  userguide.md
Labels: bug

#39 Deepscan Integration
  .github/workflows/deepscan.yml
Labels: documentation

#41 TEST
  .github/workflows/azure-deploy-f24.yml
  .github/workflows/deepscan.yml
Labels: documentation
